# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Client

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2


    - name: set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


#    - name: Set up JDK 20
#      uses: actions/setup-java@v2
#      with:
#        java-version: '17'
#        distribution: 'adopt'


    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: DMG file
        path: jpackagefx-main/target/installer/*.dmg
    - name: Upload PKG
      uses: actions/upload-artifact@v2
      with:
        name: PKG file
        path: jpackagefx-main/target/installer/*.pkg